language: common-lisp
sudo: required

env:
  global:
    - PATH=~/.roswell/bin:~/go/bin:$PATH
    - ROSWELL_BRANCH=release
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - REVIEWDOG_VERSION=0.9.0
    - COVERAGE_EXCLUDE=t
    - secure: G5LhqaVtgPCaOEuswI6qMmAnSzJ+Hki5VDW/ivUXN5BvshkggbEncOBkBW5TdzFgOsAK1zVkZsV4Qdj76TbP7WhX9Qcc7uyKdD91EbKu49PrSNJlVh7H35/QJZ2PnFve5rOUyRKIi/+gz7n7jlZEMP3i9l8M+x1mZtoUqKrpWrg=
  matrix:
    - LISP=sbcl-bin COVERALLS=true REVIEWDOG=true
    - LISP=ccl-bin

services:
  - redis-server

install:
  # Install Roswell
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh

  # Install reviewdog
  - if [ "$REVIEWDOG" ]; then
      mkdir -p ~/go/bin;
      curl -L https://github.com/haya14busa/reviewdog/releases/download/$REVIEWDOG_VERSION/reviewdog_linux_386 > ~/go/bin/reviewdog;
      chmod u+x ~/go/bin/reviewdog;
    fi
  # Install SBLint
  - if [ "$REVIEWDOG" ]; then ros install fukamachi/sblint; fi

  # Install prove
  - ros install prove

cache:
  directories:
    - "$HOME/.roswell"
    - "$HOME/.config/common-lisp"

before_script:
  - ros --version
  - ros config

script:
  - if [ "$LISP" = "ecl" ] || [ "$LISP" = "clisp" ]; then
      ls t-*.asd | grep -v t-lack-session-store-dbi.asd | xargs run-prove;
    else
      run-prove t-*.asd;
    fi
  - if [ "$REVIEWDOG" ]; then
      sblint | reviewdog -efm="%f:%l:%c %m" -diff="git diff master" -ci=travis;
    fi
